<h1 style="text-align:center"> Linear and Relu Layers from PyTorch </h1>

<img src="https://miro.medium.com/max/700/1*P9i-939Oil0jhfdUoVMJtw.jpeg" />


In [1]:
import torch
import numpy as np

In [2]:
from torch import nn

Linear layer randomly generates the wights and bias for fitting a line

<b> y = beta0 + beta1*x1 + beta2*x2 + .... + beta(n)*xn </b>

In [3]:
linear_layer = nn.Linear(in_features=3,out_features=1)
print(linear_layer.weight)
print(linear_layer.bias)

Parameter containing:
tensor([[-0.2200, -0.2142,  0.4059]], requires_grad=True)
Parameter containing:
tensor([-0.3293], requires_grad=True)


Once we created an object for nn.Linear , we could use the object to generate predictions for the particular weights and bias

In [4]:
#example 1
print(linear_layer(torch.tensor([1,2,3],dtype=torch.float32)))

tensor([0.2401], grad_fn=<AddBackward0>)


In [5]:
#example 2
print(linear_layer(torch.tensor([4,5,6],dtype=torch.float32)))

tensor([0.1553], grad_fn=<AddBackward0>)


<h2>RELU - Activation function </h2>

Relu is a function which takes in a number and returns the number if number > 0 and 0 if the number <= 0.
There are 2 ways to use relu in PyTorch

In [6]:
#relu method 1
torch.relu(torch.tensor(-50,dtype=torch.float32))

tensor(0.)

In [7]:
#relu method 2
relu = nn.ReLU()
relu(torch.tensor(50,dtype=torch.float32))

tensor(50.)