# Saving and Loading Models

<img src="https://miro.medium.com/max/700/1*WwOF2nTIuNhu1tEAe-xjgg.jpeg" />

after creating a succesful deep learning model , it is very important to save the model

In [1]:
#importing the libraires
import torch
import torch.nn as nn

In [2]:
#creating a linear model
class Model(nn.Module):
  def __init__(self):
    super(Model,self).__init__()
    self.fc1 = nn.Linear(in_features=3,out_features=5)
  
  def forward(self,x):
    return self.fc1(x)

After training the model , all we have to do is torch.save(modelname,filename). I have used .h5 file type to save the model

In [3]:
#saving the model
model = Model()
torch.save(model,'something.h5')

Similarly, we can load the model with torch.load(filename)

In [4]:
#loading the model
loaded_model = torch.load('something.h5')

In [5]:
#weights of the original model
model.fc1.weight

Parameter containing:
tensor([[ 0.0725,  0.1615, -0.0047],
        [-0.0371, -0.2640, -0.3004],
        [ 0.2129,  0.1725, -0.0136],
        [-0.5025,  0.5496,  0.0448],
        [-0.2974,  0.1040,  0.0932]], requires_grad=True)

In [6]:
#weigths of the loaded model
loaded_model.fc1.weight

Parameter containing:
tensor([[ 0.0725,  0.1615, -0.0047],
        [-0.0371, -0.2640, -0.3004],
        [ 0.2129,  0.1725, -0.0136],
        [-0.5025,  0.5496,  0.0448],
        [-0.2974,  0.1040,  0.0932]], requires_grad=True)

In [7]:
#making predictions with a loaded model
tensor = torch.tensor([[1,2,3]],dtype=torch.float32)
loaded_model(tensor)

tensor([[ 0.7429, -1.2462,  0.4356,  1.0646,  0.5010]],
       grad_fn=<AddmmBackward>)